
worker_processes  1;

events {
    worker_connections  1024;
    multi_accept on;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    tcp_nodelay on; 
    tcp_nopush on;
    limit_conn_zone $binary_remote_addr zone=addr:10m;

    upstream backend {
        server localhost:8080;
    }

    server {
        listen       80;
        server_name  localhost;


        return 301 https://$server_name$request_uri;
    }

    server {
        listen 443 ssl;
        http2 on;
        server_name localhost;
        
        # SSL сертификаты
        ssl_certificate     ../ssl/localhost.crt;
        ssl_certificate_key ../ssl/localhost.key;
        
        # Оптимизация SSL
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
        
        # Логи
        access_log logs/access.log;
        error_log logs/error.log;
        
        # Frontend статика
        location / {
            root ../../frontend/dist;
            try_files $uri $uri/ /index.html;
            
            # Кэширование статики
            expires 1d;
            add_header Cache-Control "public, immutable";
        }

        location ~* \.html$ {
                expires -1;
                add_header Cache-Control "no-cache, no-store, must-revalidate";
        }

        
        # Backend API
        location /api/ {
            proxy_pass http://backend;
            proxy_http_version 1.1;
            
            proxy_set_header Connection "";
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
            
            client_max_body_size 10G;
        }
        
        error_page 404 /404.html;
        location = /404.html {
            root ../../frontend/dist;
            internal;
        }
        
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root ../../frontend/dist;
            internal;
        }
    }
}
